/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import javax.swing.JOptionPane;
public class Program_1 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Program_1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Average_Output = new javax.swing.JTextField();
        Sum_Output = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dashboard_BTN = new javax.swing.JButton();
        Clear_BTN = new javax.swing.JButton();
        Submit_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Submit_BTN2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 153));
        jLabel4.setText("Average of the array elements:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 20));

        Average_Output.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        Average_Output.setCaretColor(new java.awt.Color(51, 0, 153));
        jPanel2.add(Average_Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 220, 40));

        Sum_Output.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        Sum_Output.setCaretColor(new java.awt.Color(51, 0, 153));
        jPanel2.add(Sum_Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 40));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Sum of the array elements:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 280, 180));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("INPUT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 60, 20));

        Input.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        Input.setCaretColor(new java.awt.Color(51, 0, 153));
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        jPanel1.add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 40));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Enter Array Size:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 170));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUM AND AVERAGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 450, 50));

        Dashboard_BTN.setBackground(new java.awt.Color(102, 0, 102));
        Dashboard_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Dashboard_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_BTN.setText("GO BACK");
        Dashboard_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Dashboard_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Dashboard_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 120, 40));

        Clear_BTN.setBackground(new java.awt.Color(204, 204, 255));
        Clear_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Clear_BTN.setForeground(new java.awt.Color(51, 0, 153));
        Clear_BTN.setText("CLEAR");
        Clear_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Clear_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 150, 60));

        Submit_BTN.setBackground(new java.awt.Color(102, 51, 255));
        Submit_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Submit_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Submit_BTN.setText("SUBMIT");
        Submit_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Submit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 540));

        Submit_BTN2.setBackground(new java.awt.Color(102, 51, 255));
        Submit_BTN2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Submit_BTN2.setForeground(new java.awt.Color(255, 255, 255));
        Submit_BTN2.setText("SUBMIT");
        Submit_BTN2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Submit_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BTN2ActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BTNActionPerformed
        try {
            int size = Integer.parseInt(Input.getText());
            double[] Array = new double[size];
            double Sum = 0, Average = 0;

            for (int i = 0; i < size; i++) {
                Array[i] = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter Number " + (i+1)));
                Sum += Array[i];
            }

            Average = Sum / size;

            Sum_Output.setText(String.valueOf(Sum));
            Average_Output.setText(String.valueOf(Average));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter numbers only.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Submit_BTNActionPerformed

    private void Submit_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BTN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_BTN2ActionPerformed

    private void Dashboard_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_BTNActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Dashboard_BTNActionPerformed

    private void Clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_BTNActionPerformed
        Input.setText("");
        Sum_Output.setText("");
        Average_Output.setText("");
    }//GEN-LAST:event_Clear_BTNActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Average_Output;
    private javax.swing.JButton Clear_BTN;
    private javax.swing.JButton Dashboard_BTN;
    private javax.swing.JTextField Input;
    private javax.swing.JButton Submit_BTN;
    private javax.swing.JButton Submit_BTN2;
    private javax.swing.JTextField Sum_Output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
