/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Program_3 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Program_3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Output = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dashboard_BTN = new javax.swing.JButton();
        Clear_BTN = new javax.swing.JButton();
        Submit_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Program_2 = new javax.swing.JButton();
        Submit_BTN2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Output.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        Output.setCaretColor(new java.awt.Color(51, 0, 153));
        jPanel2.add(Output, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 40));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("OUTPUT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 280, 180));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Input.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 153)));
        Input.setCaretColor(new java.awt.Color(51, 0, 153));
        jPanel1.add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 220, 40));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Enter a fruit to search for:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 20));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("INPUT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 170));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FINDING A SPECIFIC ELEMENT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 590, 50));

        Dashboard_BTN.setBackground(new java.awt.Color(102, 0, 102));
        Dashboard_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Dashboard_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_BTN.setText("GO BACK");
        Dashboard_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Dashboard_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Dashboard_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 120, 40));

        Clear_BTN.setBackground(new java.awt.Color(204, 204, 255));
        Clear_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Clear_BTN.setForeground(new java.awt.Color(51, 0, 153));
        Clear_BTN.setText("CLEAR");
        Clear_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Clear_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Clear_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 150, 60));

        Submit_BTN.setBackground(new java.awt.Color(102, 51, 255));
        Submit_BTN.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Submit_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Submit_BTN.setText("SUBMIT");
        Submit_BTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Submit_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 540));

        Program_2.setBackground(new java.awt.Color(204, 204, 255));
        Program_2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Program_2.setForeground(new java.awt.Color(51, 0, 153));
        Program_2.setText("SUBMIT");
        Program_2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(Program_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, 60));

        Submit_BTN2.setBackground(new java.awt.Color(102, 51, 255));
        Submit_BTN2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Submit_BTN2.setForeground(new java.awt.Color(255, 255, 255));
        Submit_BTN2.setText("SUBMIT");
        Submit_BTN2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Submit_BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BTN2ActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BTNActionPerformed
        try {
               String[] fruits = {
                   "apple", "orange", "banana", "grape", "mango", "kiwi", "pineapple",
                   "strawberry", "blueberry", "watermelon", "peach", "pear", "papaya",
                   "cherry", "fig", "plum", "apricot", "lime", "lemon", "coconut"
               };

               String search = Input.getText().trim().toLowerCase();

               if (search.isEmpty()) {
                   throw new IllegalArgumentException("Input cannot be empty.");
               }

               boolean found = false;
               for (int i = 0; i < fruits.length; i++) {
                   if (fruits[i].equalsIgnoreCase(search)) {
                       Output.setText(search + " found at index " + i);
                       found = true;
                       break;
                   }
               }

               if (!found) {
                   Output.setText(search + " not found in the array.");
               }

           } catch (IllegalArgumentException ex) {
               Output.setText(ex.getMessage()); 
           } catch (Exception ex) {
               Output.setText("An error occurred: " + ex.getMessage());
           }
    }//GEN-LAST:event_Submit_BTNActionPerformed

    private void Submit_BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BTN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Submit_BTN2ActionPerformed

    private void Dashboard_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_BTNActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Dashboard_BTNActionPerformed

    private void Clear_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_BTNActionPerformed
        Input.setText("");
        Output.setText("");
    }//GEN-LAST:event_Clear_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_BTN;
    private javax.swing.JButton Dashboard_BTN;
    private javax.swing.JTextField Input;
    private javax.swing.JTextField Output;
    private javax.swing.JButton Program_2;
    private javax.swing.JButton Submit_BTN;
    private javax.swing.JButton Submit_BTN2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
